# Generated by Django 4.2 on 2026-05-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_userrole_studentprofile_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrolled_course',
        ),
    ]
