# Generated by Django 4.2 on 2026-05-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_studentprofile_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='branch',
            field=models.CharField(default='CSE', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='year',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
